name: deploy

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install and build NPM dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g typescript
      - run: tsc
      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@7.1.0
        with:
          switches: --archive --verbose --compress --human-readable --progress --delete --delete-excluded  --exclude-from='./.rsyncignore'
          path: .
          remote_path: /home/jj125967/domains/snake.stanrogo.com/public_html/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_port: ${{ secrets.SSH_PORT }}
